workflows:
  dolphin-ios-skylander:
    name: DolphinIOS (Unsigned IPA)
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        XCODE_PROJECT: "Source/iOS/App/DolphiniOS.xcodeproj"
        XCODE_CONFIGURATION: "Release (Non-Jailbroken)"
        XCODE_SCHEME: "DiOS (NJB)"
    scripts:
      - name: List Xcode schemes
        script: |
          echo "Listing schemes for $XCODE_PROJECT"
          xcodebuild -list -project "$XCODE_PROJECT"

      - name: Install dependancies
        script: |
          brew install cmake ninja bartycrouch

      - name: Clean & Archive (no signing)
        script: |
          xcodebuild clean archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration "$XCODE_CONFIGURATION" \
            PRODUCT_BUNDLE_IDENTIFIER="com.kkmeleon.dolphinios" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/DolphiniOS.xcarchive

      - name: Package Unsigned IPA
        script: |
          mkdir -p $CM_BUILD_DIR/output
          xcrun -sdk iphoneos PackageApplication \
            -v $CM_BUILD_DIR/DolphiniOS.xcarchive/Products/Applications/*.app \
            -o $CM_BUILD_DIR/output/DolphiniOS-unsigned.ipa

    artifacts:
      - $CM_BUILD_DIR/output/*.ipa

    publishing:
      email:
        recipients:
          - "super.critique.8@gmail.com"
