workflows:
  dolphin-ios-skylander:
    name: DolphinIOS
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "dolphin-ios.xcworkspace"
        XCODE_SCHEME: "DolphiniOS"
    scripts:
      - name: Build and archive iOS
        script: |
          xcodebuild clean archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/DolphiniOS.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/DolphiniOS.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/output
    artifacts:
      - $CM_BUILD_DIR/output/*.ipa
    publishing:
      email:
        recipients:
          - "super.critique.8@gmail.com"
