workflows:
  dolphin-ios-skylander:
    name: DolphinIOS
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        XCODE_PROJECT: "Source/iOS/App/DolphiniOS.xcodeproj"
        XCODE_SCHEME: "DiOS (NJB)"  # temporaire, pour l'instant
        BUNDLE_IDENTIFIER: "com.kkmeleon.DolphiniOS"
    scripts:
      - name: List Xcode schemes
        script: |
          echo "Listing schemes for DolphiniOS.xcodeproj"
          xcodebuild -list -project "$XCODE_PROJECT"
      - name: Clean & Build
        script: |
          xcodebuild clean archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_IDENTIFIER \
            -archivePath $CM_BUILD_DIR/DolphiniOS.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/DolphiniOS.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/output
    artifacts:
      - $CM_BUILD_DIR/output/*.ipa
    publishing:
      email:
        recipients:
          - "super.critique.8@gmail.com"
